### ISSUE TITLE
Displaying an image as a question

### ISSUE THREAD

**Issue by maryHoekstra** [ResearchKit/ResearchKit#1028] opened 2017-11-09 02:04 UTC
I would like to use the RK survey framework to create a test, where each question is presented as an image. Under the image, the user would rate the image on a scale of 1 to 5 using the scale answer format. Is there a way to insert an image instead of text for the question step?

**Comment by akshay-yadav-apple** [comment] 2017-11-09 18:39
Hey @maryHoekstra,
Currently we only support imageChoiceAnswerFormat. This sounds like a great idea. Have you already started building this out for your use case? If so, we’ll be happy to help you contribute it back to the framework.

**Comment by maryHoekstra** [comment] 2017-11-09 18:57
Hi @akshay-yadav-apple, thanks for the reply! Would building this modification be relatively straightforward? What RK files should I be looking at?

**Comment by kelseydedoshka-apple** [comment] 2017-11-12 20:17
Hi @maryHoekstra - agree with Akshay that this is a great idea. I think this should be relatively straightforward to implement. I would recommend looking at the ORKInstruction step which allows you to specify images in a step. You should be able to follow a similar model in the ORKQuestionStep by adding an image property to the step and then displaying it at the top if the image isn't nil. This property could be set on the ORKQuestionStep after initialization. Please let me know if this enough to help you get started!

My thoughts are that if an image is specified along with a title and/or text then it would display below the those label(s), otherwise it could stand alone as a the form of question. I am curious your thoughts on this?

**Comment by maryHoekstra** [comment] 2017-11-20 23:36
@kelseydedoshka-apple I have been attempting to alter the ORKQuestionStep files. I've added an image property in the .h file and now I'm trying to update the .m file. Would the image have to be added in the identifier step (along with title, answer, etc.), or just in the remaining functions? Right now, I have tried to integrate it into both (see .docx file - can't attach .m file).
[ORKQuestionStep.docx](https://github.com/ResearchKit/ResearchKit/files/1489494/ORKQuestionStep.docx)

When I try to add an image to my call to ORKQuestionStep in my swift file, I get "Incorrect argument label in call (have 'identifier:title:image:answer:', expected 'identifier:title:text:answer:')"
Then, when I try to just set the new image property for the question step, I get "Value of type 'ORKQuestionStep' has no member 'image'". Any help is appreciated - I've never worked with Objective C and feel quite muddled.

In regards to your question, I agree with that formatting. If the image is supplied with a title and/or text, it should go below. If just the image is supplied, it will stand alone.

**Comment by ninoguba** [comment] 2017-11-21 00:12
Hi @maryHoekstra perhaps you may consider an easier alternative which you will use an ORKFormStep with two ORKFormItems, the first item is an ORKImageChoiceAnswerFormat and the second item is an ORKScaleAnswerFormat.  I modified the Form example in the ORKCatalog app and it looks like this:

<img width="500" alt="screen shot 2017-11-20 at 4 07 42 pm" src="https://user-images.githubusercontent.com/4361804/33047940-3c992158-ce0d-11e7-8f78-21bbd9917265.png">

The code is like:

```
    /**
    This task demonstrates a form step, in which multiple items are presented
    in a single scrollable form. This might be used for entering multi-value
    data, like taking a blood pressure reading with separate systolic and
    diastolic values.
    */
    private var formTask: ORKTask {
        let step = ORKFormStep(identifier: String(describing:Identifier.formStep), title: exampleQuestionText, text: nil)
        step.isOptional = false
        
        let roundShapeImage = UIImage(named: "hand_solid")!
        let roundShapeText = NSLocalizedString("Hand", comment: "")
        
        let imageChoces = [
            ORKImageChoice(normalImage: roundShapeImage, selectedImage: nil, text: roundShapeText, value: roundShapeText as NSCoding & NSCopying & NSObjectProtocol)
        ]
        
        // A first field, for displaying your image.
        let formItem01Text = NSLocalizedString("Your Image", comment: "")
        let formItem01 = ORKFormItem(identifier: String(describing:Identifier.formItem01), text: formItem01Text, answerFormat: ORKAnswerFormat.choiceAnswerFormat(with: imageChoces))
        
        // A second field, for the scale.
        let formItem02Text = NSLocalizedString("Your Scale", comment: "")
        let formItem02 = ORKFormItem(identifier: String(describing:Identifier.formItem02), text: formItem02Text, answerFormat: ORKAnswerFormat.scale(withMaximumValue: 5, minimumValue: 1, defaultValue: 0, step: 1, vertical: false, maximumValueDescription: nil, minimumValueDescription: nil))
        
        step.formItems = [
            formItem01,
            formItem02
        ]
        
        return ORKOrderedTask(identifier: String(describing:Identifier.formTask), steps: [step])
    }
```

**Comment by maryHoekstra** [comment] 2017-11-21 02:28
Hi @ninoguba - thank you for this wonderful suggestion. I think this might just work for my purposes. 
One concern: is there some way to disable selection on the image (or at least remove 'tap to select')?

![simulator screen shot - iphone 5s - 2017-11-20 at 21 26 06](https://user-images.githubusercontent.com/25699628/33051752-7d0709cc-ce39-11e7-8d93-9b6af217bf3e.png)

**Comment by ninoguba** [comment] 2017-11-21 03:44
Yes hiding the placeholder and selected value labels under the image is a simple customization -> change their height to 0 or make them hidden.

**Comment by ninoguba** [comment] 2017-11-21 03:53
Look for _choiceLabel and _placeHolderLabel in ORKImageSelectionView.m and setting their heights to zero would be the easiest change assuming you dont need them across your app.

**Comment by maryHoekstra** [comment] 2017-11-21 13:32
@ninoguba I have tried to make the labels hidden, but the changes aren't rendering when I run the simulator. 
`- (void)resetLabelText {
    _placeHolderLabel.hidden = YES;
    _choiceLabel.hidden = YES;
    
}

- (void)setLabelText:(NSString *)text {
    _choiceLabel.text = text;
    _choiceLabel.textColor = [UIColor blackColor];
    
    _choiceLabel.hidden = YES;
    _placeHolderLabel.hidden = YES;`

I even tried changing the placeholder text to red to test it, but nothing changed. I am modifying the ORKImageSelectionView.m file within the Pods folder of my Xcode project - is this not the correct place to do it? 

<img width="306" alt="screen shot 2017-11-21 at 8 30 05 am" src="https://user-images.githubusercontent.com/25699628/33075103-6e796604-ce96-11e7-810c-35fa239d8b2b.png">

**Comment by kelseydedoshka-apple** [comment] 2017-11-21 18:36
@ninoguba - thanks for chiming in here as well, and great suggestion for @maryHoekstra. @maryHoekstra please keep me updated here on how this approach ends up working for you?

I do still like the idea of being able to use an image as the form of question in the ORKQuestionStep and that would be a great addition to the step. As @ninoguba also mentioned some of the issues you may being seeing trying to implement this approach could be caused by the pods not rebuilding. Let me take a look at the file you provided and see if I can track down what is happening there. Would be happy to still help you down that path as well if you are interested!

**Comment by maryHoekstra** [comment] 2017-11-22 03:00
@ninoguba I'm unfortunately still not seeing any changes, even after changing the build settings. Would it be better to just remove my podfile and try to add the RK framework as an embedded binary?
 
@kelseydedoshka-apple I like the idea as well! I am more than willing to try to implement it if I can sort out why my modifications aren't working. Thanks for your help and patience.

**Comment by kelseydedoshka-apple** [comment] 2017-11-22 21:03
@maryHoekstra - not a problem at all, thank you for your continued work here! For starters as it can be hard to diagnose pod issues I would recommend trying to remove the pod file and just add the RK framework. This will at least help unblock you on some of the changes, and if you are interested in still using the pods moving forward we can see if we can tackle that issue next!

Try adding the RK framework directly to your project and then let me know which issues you are still seeing, and we can work through them from there!

**Comment by maryHoekstra** [comment] 2017-11-26 00:36
@kelseydedoshka-apple I removed cocoapods, re-downloaded RK and added it as a framework. Now changes are rendering. Unfortunately, I'm still having trouble altering the ORKInstructionStep files. Even when I try to add an image property in the .h file, I get "Unknown type name UIImage". I think that this modification would be very useful for my project, but I may just use Nino's suggestion for now. 

@ninoguba - for whatever reason, the constraints you suggested adding earlier didn't work for me. I just set the _placeholderLabel to hidden in resetLabelText() and that seemed to work. Thanks for all your suggestions.

**Comment by kelseydedoshka-apple** [comment] 2017-11-26 23:16
@maryHoekstra - great to hear you are now seeing your changes render. For editing the ORKQuestionStep.h file it looks like UIKit isn't currently imported in the file which is why you are seeing the Unknown type name error. If you add @import UIKit; at the top of the file that should solve that error. Let me know if that works for you!

**Comment by maryHoekstra** [comment] 2017-12-01 15:05
@kelseydedoshka-apple - that's embarrassing (and easy to fix). It turns out that I won't be able to use UIImages in my test, but will have to use UIViews. I image that presenting a view rather than an image in the question step would be quite a bit more complicated? I'll play around a bit but may have to implement the test without RK.

**Comment by kelseydedoshka-apple** [comment] 2017-12-01 16:57
@maryHoekstra - not a problem at all, it happens to everyone! I'm glad this helped unblock you a bit. If I understand you correctly you are trying to present a UIView instead of a UIImage? I think you can follow a similar approach as we have discussed just replacing the image property with a view property. If I am not understanding you properly please let me know.

**Comment by maryHoekstra** [comment] 2017-12-01 20:05
@kelseydedoshka-apple - I figured out the image bit so I am back to presenting images. I added an image as a property to the ORKQuestionStep.h file and tried changing the relevant functions in the .m file (initWithCoder, encodeWithCoder, isEqual, and copyWithZone). 

Should I just be able to present the image like this:
`  
    questionStep.image = UIImage(named: "imageName")!
    steps += [questionStep]
`

When I do this, no image appears in the question.

**Comment by kelseydedoshka-apple** [comment] 2017-12-02 23:31
@maryHoekstra - you are off to a great start. That should allow you to set the images like you have done so in your example. That should get you half the way there. You will have to implement
the code as well to display it. You can use the setter of the image property to either update a or create UIImageView with the set image. You will have to lay it out on the view accordingly. I would recommend also looking at the ORKInstructionStep as well for how that lays out image elements.

**Comment by maryHoekstra** [comment] 2017-12-11 14:14
@kelseydedoshka-apple - the UIImageView must be created programatically right? Within ORKQuestionStep? I don't see any code pertaining to UIImageViews in ORKInstructionStep so not sure how to go about this.

**Comment by kelseydedoshka-apple** [comment] 2017-12-11 17:01
@maryHoekstra - yes you will need to create the UIImageView programatically. 

The ORKInstructionStep boils all the way down to ORKVerticalContainerView for the image rendering but it might be easier to just look at an example online or elsewhere that is more straightforward.

Essentially you will want to create a UIImageView, then set the image property of the image passed in from the step, add it to the subview and then you will need to set the auto layout constraints for how to position it on the view.

**Comment by maryHoekstra** [comment] 2017-12-11 18:41
@kelseydedoshka-apple - this is what I would do in Swift:

`        let imageView = UIImageView(image: image!)
        imageView.frame = CGRect(x: 0, y: 0, width: 200, height: 200)
        view.addSubview(imageView)
        imageView.translatesAutoresizingMaskIntoConstraints = false
        let horizontalConstraint = NSLayoutConstraint(item: imageView, attribute: NSLayoutAttribute.centerX, relatedBy: NSLayoutRelation.equal, toItem: view, attribute: NSLayoutAttribute.centerX, multiplier: 1, constant: 0)`

Would need to convert to Obj-c. 

Will this code need to be within ORKQuestionStep? In which function?

**Comment by simon-apple** [comment] 2024-12-07 01:35
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!

**Closed by simon-apple** 2024-12-07 01:35 UTC
Labels: question
