### ISSUE TITLE
Is the stable branch defunct?

### ISSUE THREAD

**Issue by emersonf** [ResearchKit/ResearchKit#942] opened 2017-03-11 13:45 UTC
I was checking on the status of #928 and out of curiosity looked at the last time the `stable` branch was updated. It hasn't been touched for over 4 months.

There have surely been bug fixes since October, #928 included, which haven't been merged in. So what's the guidance here? Should people use the `master` branch instead of `stable`?

**Comment by rsanchezsaez** [comment] 2017-03-12 01:51
`stable` usually contains the latest "official" release by Apple, as shown [here](https://github.com/ResearchKit/ResearchKit/releases). I think that for these releases they do an extensive internal QA testing, update localized strings, make sure all assets are approved by design, and verify the public facing documentation. I don't know the schedule of these releases other than what the previous history suggests.

In general `master` is quite stable, and as you noticed, frequently contains bugfixes. I'd personally recommend using it.

**Comment by emersonf** [comment] 2017-03-12 21:21
Thanks @rsanchezsaez. I'll try to pick the last bug fix commit on `master` and lock my Podfile on that, since tracking HEAD seems like it's asking for trouble.

**Comment by kelseydedoshka-apple** [comment] 2017-03-14 16:17
@emersonf - @rsanchezsaez is correct in his response, therefore closing this issue. Thanks to Ricardo for jumping in with the quick answer.

**Closed by kelseydedoshka-apple** 2017-03-14 16:17 UTC
