### ISSUE TITLE
ORKTest should include a test of repeated identifiers in a task

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#69] opened 2015-04-21 20:02 UTC
If a task repeats the same question multiple times with the same identifier, there should be just one reported result from the task, that should include the most recent value entered.

The intermediate results reported during the task should also be accurate for each time the same identifier was presented.

We have had reports that this does not work correctly; this task is to investigate, add a test case for it in ORKTest, and fix the issue (if any).

**Comment by rsanchezsaez** [comment] 2015-04-21 22:01
Currently, if a task repeats the same *question* step multiple times using the same *identifier* the user enters an infinite loop. This is due to `ORKOrderedTask`'s `indexOfStep:` returning the index of the first duplicate step when we reach the second step. This in turn affects both `stepAfterStep:withResult:` and `progressOfCurrentStep:withResult:`.

How do you think `ORKOrderedTask` should handle this? I can think of three options:
- `ORKOrderedTask` keeps the current step index as an ivar.
- `ORKStep` has an auto-generated internal UUID for differentiating repeated steps.
- `indexOfStep:` uses the `ORKStep` object reference instead of `ORKStep`'s `isEqual:`.

Or am I misunderstanding the problem completely?

---

Also, what should happen if two completely unrelated questions on the same task happen to have the same identifier? Currently, it fails the `NSParameterAssert()` (validating the previous step answer) when you try to navigate to the different step with the repeated identifier.

Maybe we can check earlier: `ORKOrderedTask` could check that if two steps have the same *identifier* they should exactly represent the same question.

**Comment by jwe-apple** [comment] 2015-04-21 22:34
I don't think ORKOrderedTask should support this at all. It would be reasonable for ORKOrderedTask not to pass verification if it has two steps with the same identifier.

This is for a custom ORKTask, which due to how the user has answered decides to re-ask a question.

**Comment by rsanchezsaez** [comment] 2015-04-21 22:37
Is there such a custom `ORKTask` in any of the open sourced apps? Any additional details about how is this not working correctly?

**Comment by jwe-apple** [comment] 2015-04-21 23:10
In the open sourced apps, the issue came up in the consent quiz, which is a custom task that replays the quiz from the beginning if you make a mistake.

That said, to reproduce and experiment it would be easier to just create a custom task that replays the same question step indefinitely.

**Comment by rsanchezsaez** [comment] 2015-04-22 08:26
I've been able to reproduce the issue in *ShareTheJourney*: once you fail the quiz, it cannot be completed successfully upon restart.

I'll look into this.

**Comment by jwe-apple** [comment] 2015-04-22 16:37
Thanks!

**Comment by rsanchezsaez** [comment] 2015-04-22 23:17
Fixed in [pull request #95](https://github.com/ResearchKit/ResearchKit/pull/95).

**Closed** 2015-04-23 00:01 UTC
Labels: bug
