### ISSUE TITLE
I am having issues with predicateForConsent method of ORKResultPredicate

### ISSUE THREAD

**Issue by iaarpit** [ResearchKit/ResearchKit#878] opened 2016-12-09 20:11 UTC
If I tap the Agree or Disagree button, the next step it executes is "disAgreeStep" and task completes as my destinationStepIdentifier is "ORKNullStepIdentifier".

I think the rule for the "agree" is not working as it should. even tough my destinationStepIdentifier is "completionStep" it goes to the next step which is "disagreeStep".

So the step flow I want is as follows:
disagree tapped --> disagreeStep --> exit (I need direct rule to avoid "completionStep" and exit)
agree tapped --> completionStep --> exit (I need agree rule to jump to "completionStep")

```
let consentDocument = ConsentDocument()
let consentStep = ORKVisualConsentStep(identifier: String(describing: Identifier.consentStep), document: consentDocument)

let signature = consentDocument.signatures!.first!
let reviewConsentStep = ORKConsentReviewStep(identifier: String(describing:Identifier.consentReviewStep), signature: signature, in: consentDocument)
        reviewConsentStep.reasonForConsent = "By agreeing you confirm that you read the information and that you wish to take part in this research study."

 let disAgreeStep = ORKInstructionStep(identifier:String(describing:Identifier.consentDisagreeStep))
disAgreeStep.title = "Disagree."
disAgreeStep.text = ""
        
let completionStep = ORKInstructionStep(identifier:String(describing:Identifier.consentCompletionStep))
completionStep.title = "Welcome aboard."
completionStep.text = "Thank you for joining."
completionStep.image = UIImage(named: "Completion-Check")

let consentTask = ORKNavigableOrderedTask(identifier: String(describing:Identifier.consentTask), steps: [consentStep, reviewConsentStep, disAgreeStep, completionStep])

let resultSelector = ORKResultSelector(
    resultIdentifier: String(describing: Identifier.consentReviewStep))

let predicateAgree = ORKResultPredicate.predicateForConsent(
    with: resultSelector, didConsent: true)

let agreePredicateRule = ORKPredicateStepNavigationRule(
    resultPredicatesAndDestinationStepIdentifiers: [
        (predicateAgree,String(describing: Identifier.consentCompletionStep))
])

consentTask.setNavigationRule(
    agreePredicateRule,
    forTriggerStepIdentifier:String(describing:Identifier.consentReviewStep))

let consentDirectRule = ORKDirectStepNavigationRule(
    destinationStepIdentifier: ORKNullStepIdentifier)

consentTask.setNavigationRule(
    consentDirectRule,
    forTriggerStepIdentifier:String(describing:Identifier.consentDisagreeStep))

let taskViewController = ORKTaskViewController(task: consentTask, taskRun: nil)
taskViewController.delegate = self
        
present(taskViewController, animated: true, completion: nil)
```

**Comment by kelseydedoshka-apple** [comment] 2016-12-20 23:25
@iaarpit : If you don't mind could you provide a little bit more code context? It might help to see the actual steps and potentially a screen shot or two. In the meantime I have a suggestion that might help you with the issue.

You may not need the ORKDirectStepNavigationRule. If there is no navigation rule set to navigate the user to an out of order step, the steps should continue to execute in the order they are in the array.

So if you don't tap the Agree button it should automatically fall through to disagree step. And then you can just set one rule to go to the completionStep if they tap Agree.

**Comment by iaarpit** [comment] 2016-12-21 15:12
for code above, If I tap the Agree or Disagree button, the next step it executes is "disAgreeStep"  and task completes as my destinationStepIdentifier is "ORKNullStepIdentifier".

I think the rule for the "agree" is not working as it should. even tough my destinationStepIdentifier is "completionStep" it goes to the next step which is "disagreeStep".

So the step flow I want is as follows:
disagree tapped --> disagreeStep --> exit (I need direct rule to avoid "completionStep" and exit)
agree tapped --> completionStep --> exit (I need agree rule to jump to "completionStep")

**Comment by dannyiss** [comment] 2016-12-22 02:04
@iaarpit When doing predicates this is how I handled doing male/female, which is similar to agree/disagree

var resultSelectorFemale = ORKResultSelector.init(resultIdentifier: "formSex")
let predicateFemale: NSPredicate = ORKResultPredicate.predicateForChoiceQuestionResult(with: resultSelectorFemale, expectedAnswerValue: "female" as NSCoding & NSCopying & NSObjectProtocol)

Above is how I obtain a true/false if it satisfies the condition of "female", I also then check if they chose male where expected answer was "male". I then use the below code to handle both of the predicates.

predicateRuleFemale =
ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateFemale,"formPregnant"),(predicateMale,"progressLast")])

Trial using this replacing male/female with your agree/disagree. Also to find out about what the expected Answer is just print the result selector:

print("Result for Male/Female")
 print(resultSelectorFemale)

If it is a true/false then use 

let predicateSevereYes: NSPredicate = ORKResultPredicate.predicateForBooleanQuestionResult(with: resultSelector, expectedAnswer: true)

instead of predicateForChoiceQuestionResult.

**Comment by md0u80c9** [comment] 2016-12-22 15:08
Have a look at the latest ResearchKit build - the Apple team have just accepted some extra tests from my PR called PredicateTests which demonstrate all the different predicate functions and cover all these in examples.

**Comment by iaarpit** [comment] 2016-12-22 15:43
@dannyiss I am using predicateForConsent function which they have provided for ORKConsentReviewStep. I am not sure if I want to use other predicate functions for this particular step.

@md0u80c9 PredicateTests doesn't include test for predicateForConsent function.

**Comment by dannyiss** [comment] 2016-12-22 18:25
@iaarpit what is the console log of the result selector? when selecting true/false are you getting the right expected result? Also I would create a second predicate that stores the result if its false and then do as I have above by having the:

`ORKPredicateStepNavigationRule(resultPredicatesAndDestinationStepIdentifiers: [(predicateFemale,"formPregnant"),(predicateMale,"progressLast")])`

Handles two different predicates.

**Comment by iaarpit** [comment] 2016-12-22 19:18
@dannyiss console log for resultSelector is {<currentTask>, consentReviewStep, consentReviewStep}. Is there is any way to check what the selected result is and is it matching with expected result?

**Comment by kelseydedoshka-apple** [comment] 2017-01-03 23:41
@iaarpit - there are some good suggestions here any progress on resolving this issue? If not could you please provide a fuller code sample for more context?

**Comment by rsanchezsaez** [comment] 2017-01-05 18:39
The problem is that, the `resultSelector` passed to `+predicateForConsentWithResultSelector:didConsent:` must provide the desired step identifier (`stepIdentifier` argument) *and* the desired signature identifier (`resultIdentifier`  argument).

Instead of:

```
let resultSelector = ORKResultSelector(
    resultIdentifier: String(describing: Identifier.consentReviewStep)
)
let predicateAgree = ORKResultPredicate.predicateForConsent(with: resultSelector, didConsent: true)
```

yo should do:

```
let resultSelector = ORKResultSelector(
   stepIdentifier: String(describing: Identifier.consentReviewStep),
   resultIdentifier: signature.identifier
)
let predicateAgree = ORKResultPredicate.predicateForConsent(with: resultSelector, didConsent: true)

```

---

We should improve `+predicateForConsentWithResultSelector:didConsent:`'s documentation to explain this.

**Comment by kelseydedoshka-apple** [comment] 2017-01-06 02:58
@rsanchezsaez thanks for chiming in on this!

@iaarpit any luck with the above solution?

**Comment by rsanchezsaez** [comment] 2017-01-06 03:53
@iaarpit Also note that you don't probably want to pass the `consentDocument.signatures!.first!` signature to the `ORKConsentReviewStep`. Instead, I think you'd want to pass it a blank `ORKConsentSignature` object, which will be collected and filled by the `ORKConsentReviewStep`.

**Comment by iaarpit** [comment] 2017-01-06 15:04
@rsanchezsaez @kelseydedoshka-apple   Yup it works now, thanks for the help. It came to my mind that resultIdentifier should be of signatureStep, but I didn't think of using it with the stepIdentifier.

**Comment by iaarpit** [comment] 2017-01-06 15:21
@rsanchezsaez I am adding `ORKConsentSignature` object to ORKConsentDocument with addSignature function. I think it's a blank object.

**Comment by kelseydedoshka-apple** [comment] 2017-01-06 17:10
@iaarpit great glad you got it working! Thanks again to @rsanchezsaez for the assistance here as well. 

Closing this issue since it has been resolved.

**Closed by kelseydedoshka-apple** 2017-01-06 17:10 UTC
