### ISSUE TITLE
ORKVisualConsentTransitionAnimator fails to play animation

### ISSUE THREAD

**Issue by damato-digitalartefacts** [ResearchKit/ResearchKit#627] opened 2016-02-29 19:04 UTC
I've noticed an issue that causes the ORKVisualConsentTransitionAnimator to fail to play its animation. This only occurs rarely on an iPhone, but I can reproduce it about 1 in 4 times on an iPad. I expect it has to do with timing or a race condition. I have seen the issue occur on physical devices, so I can say that it is not a simulator-only issue.

The essence of the problem is that in the [ORKVisualConsentTransitionAnimator displayLinkCallback:] method, the [_videoOutput hasNewPixelBufferForItemTime] always returns NO when the bug occurs. This means that pixel buffer is never consumed and displayed.

I've limited the number of breakpoints and print statements used in displayLinkCallback due to the timing nature of the bug, but I do know that when the bug occurs, [ORKVisualConsentTransitionAnimator finish] reports the _frameCounter as 0, so the pixel buffer was never even consumed once on the bad runs. I also gathered up all the outputItemTimes computed for the bad run, and the (value / timescale) values monotonically increase from 0.0 seconds to 1.66 seconds (the duration of my animation). This seems valid, so the input to hasNewPixelBufferForItemTime should be good.

The apple documentation about the hasNewPixelBufferForItem time says this:

"This method returns YES if the video data at the specified time has not yet been acquired or is different from the video that was acquired previously. If you require multiple objects to acquire video output from the same AVPlayerItem object, you should create separate AVPlayerItemVideoOutput objects for each."

Since the _frameCounter is always 0, I imagine that the conditions for returning YES should be met because no video data was ever acquired for any time, so any data that does exist should be considered available.

I'm wondering if there is some problem with the computation of the outputItemTime that is passed to hasNewPixelBufferForItemTime. In particular, I wonder if the video output is being computed too slowly to keep up with real time, and therefore, the query time is always ahead of the available data. The docs do not seem to be clear on what happens if there is unprocessed data behind the query time.

I can explain some other idiosyncrasies of our project that may be factors.

We are using the ORKVisualConsentStepViewController a bit out of context. The animations in question are part of our survey system. We use the visual consent step to produce an intro animation and an exit animation for each survey. I'm not sure why the visual consent step would not be reusable outside of the informed consent workflow, but perhaps I've overlooked something here.

The bug occurs when going into and canceling a survey multiple times in a row. I'm not sure if it is possible to trigger the bug on the first attempt at the survey, or if the bug is somehow related to the multiple consecutive attempts, as opposed to just having to try multiple times because the bug is timing related.

I did re-write some code in the ORKVisualConsentStepViewController doAnimateFromViewController:toController:direction:url:animateBeforeTransition:transitionBeforeAnimate:completion] method. It looked like this code was setup to expect this exact sort of error to occur because there were two semaphores waiting for two conditions to occur before the transition could be completed, but those semaphores also had safety timeouts in case something went wrong. I noticed that these safety timeouts could trigger, even if the transition was interrupted by another transition and canceled. I replaced the semaphores with some booleans tagged with the '__block' keyword that were set as the two relevant conditions were met inside the completion handler blocks below. Whenever one of those booleans was updated, I run a finalization block that occurs if both are now set to YES.

That description is a bit of an aside, but that change is related to the code that drives the ORKVisualConsentTransitionAnimator, so it may be of note that I have modified that code. I'm particularly interested in the safety timeout on the semaphores, though. Have you experienced similar problems with the animation failing to complete?

If there is any other information that would be helpful in diagnosing this issue, please let me know.

**Comment by rsanchezsaez** [comment] 2016-03-01 11:35
Thanks for reporting this issue, and for investigating so thoroughly.

I did contribute some modifications to this code (including the current two semaphore design) a while ago to simplify the code and fix some issues.

> I did re-write some code in the ORKVisualConsentStepViewController doAnimateFromViewController:toController:direction:url:animateBeforeTransition:transitionBeforeAnimate:completion] method. It looked like this code was setup to expect this exact sort of error to occur because there were two semaphores waiting for two conditions to occur before the transition could be completed, but those semaphores also had safety timeouts in case something went wrong. I noticed that these safety timeouts could trigger, even if the transition was interrupted by another transition and canceled. I replaced the semaphores with some booleans tagged with the '__block' keyword that were set as the two relevant conditions were met inside the completion handler blocks below. Whenever one of those booleans was updated, I run a finalization block that occurs if both are now set to YES.

The semaphores are there because two animations need to finish before the transition is marked as completed: iOS' default push transition and the visual consent custom animation. We don't know which one will finish first (although generally the visual consent animation is longer than the iOS push transition).

The safety timeout code (do you mean `finishAndNilAnimator()`, right?) is there just in case either of the animations fail (several factors could make the video player to fail) but we were not thinking specifically about the issue that you found.

Cancelling a transition in some instances where the visual consent animation has not yet launched, would naturally made this safety timeout code to be called after 5 seconds.

Cancelling a transition after the visual consent animation has launched, should make the timeout code to be called immediately.

No ill effect should come from the safety timeout code in either of these cases.

Why did you modify this code? Did you experience issues with the previous code?

> That description is a bit of an aside, but that change is related to the code that drives the ORKVisualConsentTransitionAnimator, so it may be of note that I have modified that code. I'm particularly interested in the safety timeout on the semaphores, though. Have you experienced similar problems with the animation failing to complete?

When I made the changes, I did quite extensive testing and I couldn't get the animations to fail. However, *iOS 9* and some minor revisions have been released since then and it's possible that some internal changes started causing the issue.

Are you able to reproduce this issue with the vanilla *ResearchKit* code on the `ORKCatalog` example?

> If there is any other information that would be helpful in diagnosing this issue, please let me know.

Which iOS version and on which devices are you experiencing the problem on? Could you try using the unmodified code to see if that resolves the problem?

**Comment by umerkhan-apple** [comment] 2017-01-24 23:17
@damato-digitalartefacts Are you still experiencing this issue?

**Comment by damato-digitalartefacts** [comment] 2017-01-25 15:41
Hi Umer,

We wrapped up the project using that modified version of ResearchKit some time ago, and unfortunately, we didn’t have time in our schedule to go back and do more detailed testing and analysis to answer the questions in Ricardo’s reply. In any case, we found a work-around that worked for us, and ResearchKit is now on a new version, so I’d say go ahead and close this issue.

Thanks,

Dan

**Comment by kelseydedoshka-apple** [comment] 2017-02-23 19:11
@damato-digitalartefacts - Thanks for getting back to us. Closing this issue as suggested.

**Closed by kelseydedoshka-apple** 2017-02-23 19:11 UTC
