### ISSUE TITLE
Line Chart Pan crash when there is only one plot point

### ISSUE THREAD

**Issue by ghost** [ResearchKit/ResearchKit#699] opened 2016-06-01 12:52 UTC
I've seem to come across a bug with the line chart. Where there is only one plot point and you attempt to pan / swipe, it causes an app crash...

`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 0]'`

I've literally copied over the sample data source code into my data source and its doing the same...

```
import ResearchKit

class LineChartDataSource: NSObject, ORKGraphChartViewDataSource {

    var plotPoints =
        [
            [
                ORKRangedPoint(value: 2),
            ]
    ]

    func numberOfPlotsInGraphChartView(graphChartView: ORKGraphChartView) -> Int {
        return plotPoints.count
    }

    func graphChartView(graphChartView: ORKGraphChartView, pointForPointIndex pointIndex: Int, plotIndex: Int) -> ORKRangedPoint {
        return plotPoints[plotIndex][pointIndex]
    }

    func graphChartView(graphChartView: ORKGraphChartView, numberOfPointsForPlotIndex plotIndex: Int) -> Int {
        return plotPoints[plotIndex].count
    }

    func maximumValueForGraphChartView(graphChartView: ORKGraphChartView) -> CGFloat {
        return 70
    }

    func minimumValueForGraphChartView(graphChartView: ORKGraphChartView) -> CGFloat {
        return 0
    }

    func graphChartView(graphChartView: ORKGraphChartView, titleForXAxisAtPointIndex pointIndex: Int) -> String? {
        return "\(pointIndex + 1)"
    }

    func graphChartView(graphChartView: ORKGraphChartView, fillColorForPlotIndex plotIndex: Int) -> UIColor {
        return UIColor.clearColor()
    }
}
```

Is anyone else experiencing this? If so any idea whether we can get a fix in? Slightly urgent :)

**Comment by sukh-cohaesus** [comment] 2016-06-01 23:08
Think I've traced it down to where it's crashing. Line 221 of 

> ORKLineGraphChartView.m

`CGFloat y1 = self.yAxisPoints[plotIndex][previousValidIndex].minimumValue;`

The `previousValidIndex` here is -1

Full stack trace:

	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010d2afd85 __exceptionPreprocess + 165
		1   libobjc.A.dylib                     0x000000010fb01deb objc_exception_throw + 48
		2   CoreFoundation                      0x000000010d18d804 -[__NSArrayM objectAtIndex:] + 212
		3   ResearchKit                         0x000000010cd551c0 -[ORKLineGraphChartView canvasYPointForXPosition:plotIndex:] + 432
		4   ResearchKit                         0x000000010cd22366 -[ORKGraphChartView updateScrubberLineAccessories:plotIndex:] + 70
		5   ResearchKit                         0x000000010cd22152 __62-[ORKGraphChartView updateScrubberViewForXPosition:plotIndex:]_block_invoke.261 + 98
		6   UIKit                               0x000000010e636838 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 582
		7   UIKit                               0x000000010e636d30 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:] + 63
		8   ResearchKit                         0x000000010cd21ee4 -[ORKGraphChartView updateScrubberViewForXPosition:plotIndex:] + 500
		9   ResearchKit                         0x000000010cd21a80 -[ORKGraphChartView handlePanGesture:] + 640
		10  UIKit                               0x000000010ea7db28 _UIGestureRecognizerSendTargetActions + 153
		11  UIKit                               0x000000010ea7a19a _UIGestureRecognizerSendActions + 162
		12  UIKit                               0x000000010ea78197 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 843
		13  UIKit                               0x000000010ea80655 ___UIGestureRecognizerUpdate_block_invoke898 + 79
		14  UIKit                               0x000000010ea804f3 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 342
		15  UIKit                               0x000000010ea6de75 _UIGestureRecognizerUpdate + 2634
		16  CoreFoundation                      0x000000010d1d4c37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
		17  CoreFoundation                      0x000000010d1d4ba7 __CFRunLoopDoObservers + 391
		18  CoreFoundation                      0x000000010d1ca7fb __CFRunLoopRun + 1147
		19  CoreFoundation                      0x000000010d1ca0f8 CFRunLoopRunSpecific + 488
		20  GraphicsServices                    0x0000000114a4bad2 GSEventRunModal + 161
		21  UIKit                               0x000000010e585f09 UIApplicationMain + 171
		22  Steps                               0x000000010ca01f22 main + 114
		23  libdyld.dylib                       0x000000011137992d start + 1
	)

**Comment by YuanZhu-apple** [comment] 2016-06-02 00:00
@sukh-cohaesus Thanks for reporting this bug.

You can do a quick fix in the framework, by replacing 
`CGFloat y1 = self.yAxisPoints[plotIndex][previousValidIndex].minimumValue`
with
`CGFloat y1 = self.yAxisPoints[plotIndex][MAX(0, previousValidIndex)].minimumValue`.

Also do the same thing in line 184.

**Comment by stevebaranski** [comment] 2018-11-19 21:43
At the moment, I am unable to reproduce this issue. 

It appears that [this commit](https://github.com/ResearchKit/ResearchKit/pull/633/commits/f9d49594fe73a6a564e55b6d6ad9803089cf42a7) resolved it.

Subsequently, I believe this is eligible for closure.

**Comment by rsanchezsaez** [comment] 2018-11-20 05:53
Thanks for verifying this and referencing the fix commit! Closing.

**Closed by rsanchezsaez** 2018-11-20 05:53 UTC
Labels: bug
