### ISSUE TITLE
Is there a question format that can include an image?

### ISSUE THREAD

**Issue by davwillev** [ResearchKit/ResearchKit#1138] opened 2018-07-21 11:42 UTC
Having looked through the various question formats in RK, I cannot see an option for a text question that allows an image to be integrated as the subject of the question.

For example, in phobia research, there are paper questionnaires that include an image of what creates the anxiety, and the participant is asked to rate their level of anxiety in response to the image (scale question). This can also be done with a video instead of an image.
In pain research there are paper questionnaires that have used graphs to illustrate the pattern of the pain (yes/no question).
In dermatology resarch, participants are asked if their mole looks like certain examples (yes/no question).

Is this option possible currently, or would it need a completely new answer format?

Many thanks

**Comment by davwillev** [comment] 2018-07-23 19:48
I know, but it's not ideal. There are an increasing number of paper questionnaires that integrate an image within the body of the question (see example below, using the REDCap system). This is important as they can 'assess' how they are currently feeling, as against how they just felt (participant recall is a problem, even over short periods of time). In electronic data collection systems (including those built with ResearchKit) videos could be used, which thus far hasn't been used much.

<img width="790" alt="screen shot 2018-07-22 at 16 23 05" src="https://user-images.githubusercontent.com/35876659/43099262-84ed9548-8eb9-11e8-9466-e846de1f0dd6.png">

**Comment by ninoguba** [comment] 2018-07-23 21:15
Here's a quick hack for you using a ORKFormStep with two form items - first is a ORKImageChoiceAnswerFormat with only one image, and second a ORKScaleAnswerFormat.

<img width="497" alt="screen shot 2018-07-23 at 2 12 42 pm" src="https://user-images.githubusercontent.com/4361804/43103314-8462be8c-8e82-11e8-8983-7bab4e924f7f.png">


Here's the dirty code:

```
        let step = ORKFormStep(identifier: "ImageStep", title: nil, text: "How fearful are you of bending forwards towards the floor while keeping your knees straight?")
        
        // A first field, for entering showing the image.
        let imageChoces = [
            ORKImageChoice(normalImage: UIImage(named: "custom")!, selectedImage: nil, text: nil, value: "" as NSCoding & NSCopying & NSObjectProtocol),
        ]
        let imageAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: imageChoces, style: .singleChoice, vertical: true)
        
        let formItem01 = ORKFormItem(identifier: String(describing:Identifier.formItem01), text: nil, answerFormat: imageAnswerFormat)
        
        // A second field, for entering the scale.
        let scaleAnswerFormat = ORKAnswerFormat.continuousScale(withMaximumValue: 1.0, minimumValue: 0.0, defaultValue: -1.0, maximumFractionDigits: 0, vertical: false, maximumValueDescription: "Maximum Fear", minimumValueDescription: "No Fear")
        
        let formItem02 = ORKFormItem(identifier: String(describing:Identifier.formItem02), text: nil, answerFormat: scaleAnswerFormat)
        
        step.formItems = [
            formItem01,
            formItem02
        ]
        
        let task = ORKOrderedTask(identifier: "ImageTask", steps: [step])
```

I know this is just a hack but it is what is currently possible.  Hope this helps.

**Comment by davwillev** [comment] 2018-07-23 21:41
That is pretty impressive, I have to say.
An 'off the shelf' option would be great, but this is pretty cool! Thanks.

**Comment by ninoguba** [comment] 2018-07-23 21:47
You can take a look at the ORKInstructionStepView and adapt the relevant parts of it to ORKFormStepViewController if you want a nicer fit for your image.

**Comment by davwillev** [comment] 2018-07-23 21:50
This is great - thank you very much.

**Comment by ninoguba** [comment] 2018-07-26 21:19
This is actually a duplicate of #1028

**Comment by ninoguba** [comment] 2018-07-26 21:30
@davwillev yes please.

**Closed** 2018-07-26 21:31 UTC
Labels: tech question
