### ISSUE TITLE
ORKAudioGenerator doesn't stop when you send the app to background

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#194] opened 2015-05-17 18:36 UTC
`ORKAudioGenerator` (used by the *tone audiometry task*) doesn't stop playing when you send the app to the background.

Steps to reproduce:
1. Open the *tone audiometry task*.
2. Go to the second *tone audiometry instruction step*: a sound frequency is played.
3. Send the app to the background.
4. Listen as the tone continues playing indefinitely.

`ORKAudioGenerator` should stop when the app is sent to the background, and resume when you return to the app.

**Comment by rsanchezsaez** [comment] 2015-05-17 18:37
@vtourraine: Could you have a look at this? Thanks.

**Comment by vtourraine** [comment] 2015-05-17 20:07
@rsanchezsaez Thanks for the feedback, but I’ve just checked, and the sound stops when the app (`ORKCatalog`) goes to the background, and resumes once it comes to the foreground. Granted, there’s no code specific to the tone audiometry task to handle that situation, but iOS seems to deal with it just fine. 

Is anyone else seeing/hearing this?

**Comment by rsanchezsaez** [comment] 2015-05-17 20:17
Weird! That doesn't seem to be the case on my *iPhone 6*, with `ORKCatalog` as well. The sound keeps going indefinitely, it even precludes other apps from playing sound!

**Comment by jwe-apple** [comment] 2015-05-18 22:33
I've also seen this once on iOS 8.3, but couldn't reproduce it.

**Comment by rsanchezsaez** [comment] 2015-05-18 23:28
On my device, the issue seems to happen every time.

**Comment by jwe-apple** [comment] 2015-05-21 03:56
I have a fix for this in an upcoming PR. Assigning to me.

**Comment by rsanchezsaez** [comment] 2015-05-21 19:09
Just curious, do you know why this was affecting my device but not Vincent's?

**Comment by jwe-apple** [comment] 2015-05-21 19:47
In my testing there was some variation by iOS version. He hasn't reported his version or hardware, so not sure.

**Closed** 2015-05-21 19:47 UTC

**Comment by jwe-apple** [comment] 2015-05-21 19:50
Believed fixed in #214

**Comment by vtourraine** [comment] 2015-05-24 09:43
Hey guys, sorry I was _Away From Keyboard_ with week. Glad this is fixed. (I was using the latest public iOS version, 8.3).
