### ISSUE TITLE
Review step not considering changes that would nullify a rule.

### ISSUE THREAD

**Issue by AymanRadid** [ResearchKit/ResearchKit#819] opened 2016-09-09 10:52 UTC
I have a task with the following steps:
- (Step 1) A multiple text choices step with one last choice "Others" that if selected would bring the user to step 2
- (Step 2) A text answer step where the user can provide additional text answers. This step is only shown if the user selected "Others" in step 1
- (Step 3) A review step

If we select "Others" and put additional text answers, we will have a review step like [this](https://cloud.githubusercontent.com/assets/4644467/18384481/08509b4a-768b-11e6-9475-92ee84e2290c.png)

But if we change the answer to step 1 by removing "Other" the expected result would be to not have any answer for step 2 considering there is no other answer needed. But the review step would look like [this](https://cloud.githubusercontent.com/assets/4644467/18384458/df66c48e-768a-11e6-85c1-fa5f67bc2a13.png) anyway.

Which leads to my question, is there a way to remove the review for step 2 if we change step 1?

For the record here is the how I implemented the rule:

```
var choices = [ORKTextChoice]()

        for i in 0...3 {
            choices.append(ORKTextChoice(text: "Choice #\(i)", value: i))
        }

        choices.append(ORKTextChoice(text: "Other", value: -2))

        let medicationStepAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormatWithStyle(.MultipleChoice, textChoices: choices)
        let medicationStep = ORKQuestionStep(identifier: "medicationStep", title: medicationStepTitle, answer: medicationStepAnswerFormat)

        let reviewStep = ORKReviewStep(identifier: "reviewStep")
        reviewStep.title = medicationStepTitle

        let fieldAnswerFormat = ORKTextAnswerFormat(maximumLength: 0)
        fieldAnswerFormat.multipleLines = true
        let othersStep = ORKQuestionStep(identifier: "othersStep", title: "Please write any other medications you are taking separated by a comma", answer: fieldAnswerFormat)


        let steps = [medicationStep,othersStep,reviewStep]

        let selectedOther: NSPredicate = ORKResultPredicate.predicateForChoiceQuestionResultWithResultSelector(ORKResultSelector(resultIdentifier: "medicationStep"), expectedAnswerValue: -2)
        let navigationRule = ORKPredicateStepNavigationRule.init(resultPredicates: [selectedOther], destinationStepIdentifiers: [othersStep.identifier], defaultStepIdentifier: reviewStep.identifier, validateArrays: false)

        let task = ORKNavigableOrderedTask(identifier: "medicationTask", steps: steps)
        task.setNavigationRule(navigationRule, forTriggerStepIdentifier: medicationStep.identifier)
```

**Comment by oliverschaefer** [comment] 2016-09-12 20:45
@AymanRadid The current implementation includes every step that is managed by the task view controller. By design it works with every kind of task and pays no attention to step navigation rules.

**Comment by umerkhan-apple** [comment] 2017-01-24 22:17
@AymanRadid Before display the reviewStep, you can check the taskResult to see if the answer to Step1 is not Other and if there is an answer for Step2 and just nil the result for Step2.

**Comment by kelseydedoshka-apple** [comment] 2017-02-15 21:35
@AymanRadid - just checking in here to see if the suggestions above helped you resolve your issue?

**Comment by AymanRadid** [comment] 2017-02-16 09:09
Unfortunately I no longer work on this project as of late November, so I can't test this suggestion. What we ended up doing is removing the review step on this task.

**Comment by kelseydedoshka-apple** [comment] 2017-02-16 17:54
@AymanRadid - apologies for not getting back to you sooner so we could help you resolve this issue while you were still working on the project. Closing this issue since you were able to work around it.

**Closed by kelseydedoshka-apple** 2017-02-16 17:54 UTC
Labels: question
