### ISSUE TITLE
Build with Xcode 13 error

### ISSUE THREAD

**Issue by zxcheergo** [ResearchKit/ResearchKit#1480] opened 2021-11-30 03:08 UTC
When I try to build ResearchKit with the latest Xcode 13.1, I got an error: 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead. Can anyone tell me how to fix this ?

**Comment by j-dogcoder** [comment] 2022-01-10 16:21
Also getting this error.

**Comment by j-dogcoder** [comment] 2022-01-10 16:22
@aplummer-apple, can you help with this?

**Comment by j-dogcoder** [comment] 2022-01-10 18:32
Maybe @apple-bot?

**Comment by akshay-yadav-apple** [comment] 2022-01-10 19:13
Hey @j-dogcoder, @zxcheergo,
I tried to reproduce the issue on multiple Xcodes including most recent 13.2.1, and on various iOS builds, but unfortunately was unable to get this error. 
To narrow down the issue, could you please send which iOS version are you trying this on, and is it simulator or actual device?

**Comment by j-dogcoder** [comment] 2022-01-10 21:59
Thank you for the response @akshay-yadav-apple! I am on the simulator, building to an iPhone 12 on IOS 15.0 (my project), the deployment target for ResearchKit its self is set to 12.0 per the recommendation of Xcode.

**Comment by j-dogcoder** [comment] 2022-01-10 22:25
<img width="1164" alt="Recover — Recover xcodeproj Xcode UAeZ5pTD" src="https://user-images.githubusercontent.com/65788728/148848743-e6a8332c-9c62-4009-87f2-ac6fcff2faa1.png">

**Comment by j-dogcoder** [comment] 2022-01-12 14:56
@akshay-yadav-apple, just checking back in....

**Comment by j-dogcoder** [comment] 2022-01-15 02:40
**@akshay-yadav-apple??**

**Comment by j-dogcoder** [comment] 2022-01-17 01:34
@apple-bot

**Comment by j-dogcoder** [comment] 2022-01-18 13:38
This is still reproducible on my end.

**Comment by j-dogcoder** [comment] 2022-01-25 17:23
Just following up @akshay-yadav-apple...

**Comment by Pariecemckinney-apple** [comment] 2022-01-26 18:13
Hello @j-dogcoder, thank you for following up on this issue! We're currently in the process of creating a fix and will submit a PR as soon as its ready. I'll make sure to ping you here once the fix is in.

**Comment by j-dogcoder** [comment] 2022-01-26 18:40
Thank you so much!

**Comment by Pariecemckinney-apple** [comment] 2022-02-18 17:54
Hello @j-dogcoder, a PR has been pushed to the main branch which should allow you to point ResearchKit to IOS 15. Feel free to test this out and let me know how things go for you. A push to stable will be made after a bit more testing is done!

**Comment by j-dogcoder** [comment] 2022-02-18 18:58
Hey @Pariecemckinney-apple, trying to add the package via the URL. I get the error
<img width="661" alt="Untitled Xcode MNCtmSzS" src="https://user-images.githubusercontent.com/65788728/154745361-24401004-f26b-4724-bed2-0f67bd7105e5.png">

**Comment by j-dogcoder** [comment] 2022-02-18 19:05
any thoughts on where package.swift could have gone?

**Comment by Pariecemckinney-apple** [comment] 2022-02-18 19:41
Hey @j-dogcoder, there is currently no spm support for ResearchKit. Only CareKit at the moment.

**Comment by j-dogcoder** [comment] 2022-02-18 19:51
> Hey @j-dogcoder, there is currently no spm support for ResearchKit. Only CareKit at the moment. 

@Pariecemckinney-apple Is SPM an easy PR I could make? Or is it something more involved?

**Comment by jscubida** [comment] 2022-02-18 19:57
@j-dogcoder I wish https://github.com/ResearchKit/ResearchKit/issues/1111 was easy

**Comment by SwiftNativeDeveloper** [comment] 2022-02-22 17:49
@Pariecemckinney-apple 

Just FYI, the framework is now set to iOS 15+, checking out main and trying to build for < 15 fails right away due to minimum target. Some of the code added uses new iOS 15 symbols and wasn't protected with appropriate if version checks. I created an issue for this here #1489

> Hello @j-dogcoder, a PR has been pushed to the main branch which should allow you to point ResearchKit to IOS 15. Feel free to test this out and let me know how things go for you. A push to stable will be made after a bit more testing is done!

**Comment by j-dogcoder** [comment] 2022-02-22 21:41
Installed on my machine, and working no problem!

**Comment by Pariecemckinney-apple** [comment] 2022-07-08 17:40
Issue resolved. Closing!

**Closed by Pariecemckinney-apple** 2022-07-08 17:40 UTC
