### ISSUE TITLE
ORKCompletionStep checkmark auto layout issue

### ISSUE THREAD

**Issue by umerkhan-apple** [ResearchKit/ResearchKit#864] opened 2016-11-09 01:50 UTC
![simulator screen shot nov 7 2016 11 44 24 am](https://cloud.githubusercontent.com/assets/13040996/20124519/df37977e-a5db-11e6-984b-6d4195e6069a.png)

**Comment by huever** [comment] 2016-11-17 23:51
Solved this replacing **layoutSubviews** Method **ORKCompletionStepViewController.m** with

```
- (void)layoutSubviews {
    [super layoutSubviews];
    CGRect rect = CGRectMake(self.bounds.size.width, self.layer.frame.origin.y, TickViewSize, TickViewSize);
    self.layer.frame = rect;
}
```

Maybe this could help with this bug

**Comment by ninoguba** [comment] 2016-11-30 23:57
This was addressed by #821 but @huever's fix looks much simpler.

**Comment by syoung-smallwisdom** [comment] 2016-12-01 21:21
Duplicate of https://github.com/ResearchKit/ResearchKit/issues/820
Addressed by https://github.com/ResearchKit/ResearchKit/pull/821

I chose to address using constraints b/c while the code is longer, using constraints rather than hacking the layout does not risk reintroduction of this bug when Apple changes the rules for iOS 11. ;)

**Comment by ninoguba** [comment] 2016-12-09 18:23
PR #831 fixes this

**Comment by kelseydedoshka-apple** [comment] 2016-12-16 23:46
#831 has been merged and therefore fixes this issue.

**Closed by kelseydedoshka-apple** 2016-12-16 23:46 UTC
Labels: bug
