### ISSUE TITLE
Undefined symbols for architecture x86_64 ORKESerializer

### ISSUE THREAD

**Issue by khanxc** [ResearchKit/ResearchKit#614] opened 2016-01-28 04:35 UTC
```Swift
_OBJC_CLASS_$_ORKESerializer", referenced from:
      type metadata accessor for __ObjC.ORKESerializer in ViewController.o
ld: symbol(s) not found for architecture x86_64
```
Having this issue in Xcode 7.x +, Swift 2.x

**Comment by rsanchezsaez** [comment] 2016-03-01 12:18
Can you try with the tip of the `master` branch?

If the problem still persists, can you post a project reproducing the issue to *GitHub*?

**Comment by rsanchezsaez** [comment] 2016-08-30 07:17
@YuanZhu-apple: I think this is a duplicate of [Issue #649](https://github.com/ResearchKit/ResearchKit/issues/649) and can be closed.

**Closed** 2016-08-30 17:33 UTC
