### ISSUE TITLE
Implement size class support

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#290] opened 2015-06-10 00:04 UTC
Replace fixed device metrics by device size class support. Specially relevant in order to properly support iPad multitasking.

**Comment by jwe-apple** [comment] 2015-06-10 00:18
Yes indeed. On the ios9 branch, there have been specific issues identified which this should aim to fix:
- Image capture task rotating with a split screen can crash <rdar://problem/21191705>
- Image choice step can crash under rotation with split screen <rdar://problem/21169048>
- Scale answer formats lay out particularly badly in split screen <rdar://problem/21168750>

Note that you can't completely replace the fixed device metrics, since even for regular vertical size class, ResearchKit has multiple metric configurations. For the most part, only the metrics that depend on or affect horizontal spacing should really move to use size class.

**Comment by brucehappy** [comment] 2015-06-10 00:52
@jwe-apple, any chance we might be able to bridge the internal radar tracker with the github issue tracker for ORK?  I'm sure its a tall order.  But if its not possible, then encouraging internal apple folks to use the github tracker for new ORK issues?

**Comment by jwe-apple** [comment] 2015-06-10 02:06
No chance for a bridge I'm afraid. We generally do this manually, where the issue is suitable for public consumption. Clearly, before yesterday we couldn't have posted these ;-)

**Comment by brucehappy** [comment] 2015-06-10 02:31
Ok, I certainly understand the timing, and that it'll be a manual process.  Now I guess I just need an iPad Air 2 to test with :smiley:

**Comment by rsanchezsaez** [comment] 2015-08-18 22:18
Probably this is no longer needed due to the solution implemented by Yuan in [PR #370](https://github.com/ResearchKit/ResearchKit/pull/370).

**Comment by kelseydedoshka-apple** [comment] 2017-01-17 18:26
@rsanchezsaez closing this issue due to the merged solution you mentioned above!

**Closed by kelseydedoshka-apple** 2017-01-17 18:26 UTC
