### ISSUE TITLE
Knee and Shoulder Range of Motion Issue

### ISSUE THREAD

**Issue by HEIDEMAN** [ResearchKit/ResearchKit#930] opened 2017-03-01 17:06 UTC
I am trying to implement the active tasks for Knee and Shoulder range of motion, but it seems to be crashing on step 5 of 7 where it asks you to place the device and touch anywhere to continue.

Any ideas on how to fix this? Some of the errors are:

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Expect result object to be `ORKStepResult` type and not nil: {knee.range.of.motion : <ORKRangeOfMotionResult: flexion: 0.000000; extension: 0.000000>}
and
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Expect result object to be `ORKStepResult` type and not nil: {shoulder.range.of.motion : <ORKRangeOfMotionResult: flexion: 90.000000; extension: 90.000000>}'

**Comment by HEIDEMAN** [comment] 2017-03-01 17:07
return ORKOrderedTask.shoulderRangeOfMotionTask(withIdentifier: surveyIdentifier, limbOption: .left, intendedUseDescription: nil, options: [])

 and

return ORKOrderedTask.kneeRangeOfMotionTask(withIdentifier: surveyIdentifier, limbOption: .right, intendedUseDescription: nil, options: [])

**Comment by syoung-smallwisdom** [comment] 2017-03-01 17:36
@HEIDEMAN 
The problem is that the step result is not being created properly. This issue has been found and fixed in https://github.com/ResearchKit/ResearchKit/pull/902 but that pull request has not been accepted yet. I just updated it and if you want to point at that branch, you should be good.

@umerkhan-apple @kelseydedoshka-apple 
Could you please take a look at https://github.com/ResearchKit/ResearchKit/pull/902 and https://github.com/ResearchKit/ResearchKit/pull/910. These lingering pull requests make it difficult for us to actually use the ResearchKit fork. We have to maintain our own fork with fixes for the bugs and issues we find and the bookkeeping is really time consuming.

**Comment by syoung-smallwisdom** [comment] 2017-03-01 17:41
@HEIDEMAN You can also point at our main fork: https://github.com/Sage-Bionetworks/ResearchKit We try to keep it updated with fixes to ResearchKit/master from other developers who are contributing to the code base but it also includes all the outstanding pull requests that have been accepted into our repo but not yet accepted by Apple.

**Comment by umerkhan-apple** [comment] 2017-03-14 18:48
@syoung-smallwisdom Thank you for contributing the fixes to the result objects in those PRs.

**Comment by umerkhan-apple** [comment] 2017-03-14 19:04
@syoung-smallwisdom Merged!

**Closed by umerkhan-apple** 2017-03-14 19:04 UTC

**Comment by syoung-smallwisdom** [comment] 2017-03-14 19:54
Thanks!
