### ISSUE TITLE
State restoration makes the image capture step to fail

### ISSUE THREAD

**Issue by rsanchezsaez** [ResearchKit/ResearchKit#242] opened 2015-06-01 01:05 UTC
Restoring the app to an image capture step makes the view controller unstable.

*Steps to reproduce*
1. Launch `ORKTest` from Xcode.
2. Open the *Image Capture* task.
3. Go to step 4 (image capture step).
4. Send the app to background and hit stop on Xcode so the state is stored.
5. Launch `ORKTest` again, it should restore to the image capture step.
6. Try capturing an image.

If you try to capture an image after state restoration, a zoomed portion of the image is shown on screen and a *"The captured image could not be saved"* error is shown.

If you then tap "*Recapture image*", the layout of the hand template breaks and the error message is not dismissed. If you press "Capture", it goes to the next step instead of capturing a new image. Capture also fails when you reach *step 7* (additional image capture step).

Ending the task and restarting it fixes it.

**Comment by jwe-apple** [comment] 2015-06-01 02:15
Is the output directory correctly set on the image capture step VC during restoration?

**Comment by jwe-apple** [comment] 2015-06-01 17:57
Reproduced.

**Comment by brucehappy** [comment] 2015-06-01 18:04
I'd love to reproduce and fix, but I'm tied up today.  The soonest I could get to it is tomorrow afternoon.

**Comment by rsanchezsaez** [comment] 2015-06-01 23:45
> Is the output directory correctly set on the image capture step VC during restoration?

The problem seems to be related to the output directory indeed. The output directory *ivar* is correctly being set during restoration. And checking with iExplorer, I can see the output directory existing on the device.

After restoration, however, `[_capturedImageData writeToURL:url options:NSDataWritingAtomic|NSDataWritingFileProtectionCompleteUnlessOpen error:&writeError]` fails with this error:

    2015-06-02 00:39:47.983 ORKTest[3750:765665] [ORK][OOPS] -[ORKImageCaptureStepViewController writeCapturedDataWithError:] 249 Error Domain=NSCocoaErrorDomain Code=4 "The operation couldn’t be completed. (Cocoa error 4.)" UserInfo=0x170266500 {NSFilePath=/var/mobile/Containers/Data/Application/AFB848AA-F633-460F-871E-F5BD600AF3C6/Documents/350FE580-3955-42AC-9F50-0BB2E0ED1A8E/right3.jpg, NSUnderlyingError=0x170249de0 "The operation couldn’t be completed. No such file or directory"}


I tried creating the output directory again just before saving the captured image, but I get this error:

    Error Domain=NSCocoaErrorDomain Code=513 "The operation couldn’t be completed. (Cocoa error 513.)" UserInfo=0x1702667c0 {NSFilePath=/var/mobile/Containers/Data/Application/AFB848AA-F633-460F-871E-F5BD600AF3C6/Documents/350FE580-3955-42AC-9F50-0BB2E0ED1A8E, NSUnderlyingError=0x170250590 "The operation couldn’t be completed. Operation not permitted"}

I'm not sure what's going on, I think it may be related to data protection.

---

Independently of fixing the *image writing issue*, the image capture view controller could handle the error better.

**Comment by jwe-apple** [comment] 2015-06-02 06:57
Fixed by #252.

**Comment by jwe-apple** [comment] 2015-06-02 19:26
Fixed.

**Closed by jwe-apple** 2015-06-02 19:26 UTC

**Comment by rsanchezsaez** [comment] 2015-06-02 23:53
Hey @brucehappy, John fixed the root of the issue (wrong output directory after restoration), but still `ORKImageCaptureStepViewController` doesn't handle image write errors very gracefully.

You can artificially reproduce this by adding `url = [NSURL fileURLWithPath:@"/"];` just before `writeToURL:...` in `writeCapturedDataWithError:`.

Notice how, when doing this, after `ORKImageCaptureView`'s `setError:`:
1. Constraints are wrongly recalculated after the error, the `previewView` stays visible and overflows the screen.
2. Tapping recapture doesn't clear the error, nor the preview image. The constraints for the `previewView` remain incorrect.
3. When you try to recapture, it goes to the next step because it still has the preview image (even though it has not been saved to disk). 

Also, apart from the error, rotating while on the image capture step doesn't recalculate the constraints and the view layout (so if you go from landscape to portrait, the bottom remains semitransparent and partially overlapping the camera feed).

Do you have time to look into this? I can try and fix it later if you don't.

**Comment by brucehappy** [comment] 2015-06-03 05:42
I am taking a look now.  Was surprised with the latest changes to layout, which I documented on #246.  I'll see if I can handle this error now.

**Comment by jwe-apple** [comment] 2015-06-03 06:13
@brucehappy Yep, looks like I didn't give that one adequate review.

**Comment by brucehappy** [comment] 2015-06-03 08:09
Should be resolved with PR #263

**Comment by rsanchezsaez** [comment] 2015-06-03 10:20
Actually, I missed the layout problem during review of [PR #250](https://github.com/ResearchKit/ResearchKit/pull/250). Fixed now in [PR #265](https://github.com/ResearchKit/ResearchKit/pull/265).
